### ISSUE TITLE
Confirm Lee Filter works as intended

### ISSUE THREAD

**Issue by thodorii** [thodorii/Thesis#3]
Currently Lee filter takes in the entire image with all the channels and does cv2 2dfilter stuff on it.

- Channels 1,2 are co-event SAR (VV, VH)
- Channels 3,4 are pre-event SAR  (VV, VH)
- Channels 5,6 are co-event coherence InSAR and pre-event InSAR

We need to make sure that when the lee filter is applied, it is applied to _**each channel seperately**_

Should be easy to do with a binary image with each channel occupying a unique space in that image. 

**_TODO_** 
- [x] Implement this test
- [x] Confirm working?

**Comment by ThodoriKapouranis** [comment]
Lee filter does not work properly, it is doing it across channels **_which is undesired_** 

Notice the ghosting

![lee-test](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/8dd7e184-d479-499d-a998-6e752eac6e3a)

- [ ] FIX

**Comment by ThodoriKapouranis** [comment]
![lee-test](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/7a0cfb55-22a5-437b-ad3b-7dbf9f5ec7c5)

![Bolivia_2278758_S1Weak](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/3a665d71-67a3-4c85-9318-e749c15b2e4a)

**Comment by ThodoriKapouranis** [comment]
Some Psuedocolor
![Mekong_9738641_S1Weak](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/fbca5d71-4a02-4dd7-8337-6af4c592cd0e)
![Paraguay_61696_S1Weak](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/11d543a9-f20f-4e93-b352-636678e7e871)
![USA_208966_S1Weak](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/6193a2bb-fef9-48de-97a2-ec208e05bdee)
![Mekong_6385302_S1Weak](https://github.com/ThodoriKapouranis/Thesis/assets/51767101/693de9b9-8632-47d5-b98a-adc6f1e84a0b)
